ApollosProject/apollos-embeds

- src/components/Auth/AuthDetails.js
- src/ui-kit/Select/Select.js
- src/ui-kit/Select/Select.styles.js
- src/ui-kit/Select/index.js
- src/ui-kit/index.js
[🛠️ Make gender input a dropdown](https://3.basecamp.com/3926363/buckets/27088350/todos/5881995171)
1. Added Select component to ui_kit
2. Use Select to create dropdown for gender input
> 🛠️ Make gender input a dropdown

- src/components/FeatureFeed/FeatureFeedComponentMap.js
- src/components/FeatureFeed/Features/VerticalCardListFeature.js
- src/components/FeatureFeed/Features/VerticalCardListFeature.styles.js
- src/components/FeatureFeed/Features/index.js
- src/ui-kit/ContentCard/ContentCard.js
- src/ui-kit/ContentCard/ContentCard.styles.js
- src/ui-kit/_config/theme.js
[⭐️ Create VerticalCardList Feature component](https://3.basecamp.com/3926363/buckets/27088350/todos/5882084674)
1. Add new VerticalCardListFeature component
2. Display items in this order:
- If there is only 1 card => Use a horizontal content card
- 1440px and more => 2 rows, 3 columns
- 1280px - 1440px => 3 rows, 2 columns
- 768px or less => 1 column
3. Will show a maximum of 6 cards
https://user-images.githubusercontent.com/68402088/226702525-a55b6df3-e862-4723-99f0-d4cf2a4c3a6e.mov
> ⭐️ Create VerticalCardList Feature component

- src/hooks/useTabFeed.js
- src/ui-kit/ContentCard/ContentCard.js
- src/ui-kit/MediaItem/MediaItem.js
Fix checkmark color and passes breadcrumb title correctly
> Bug clean up

- src/components/ContentSingle.js
- src/components/FeatureFeed/Features/HorizontalCardListFeature.js
- src/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- src/components/LivestreamSingle.js
Fixes child items on ContentSingle and LivestreamSingle views. So, series items should show up correctly now.
> Fix ContentSingle and LivestreamSingle child items

- public/index.html
- src/components/Auth/AuthLayout/AuthLayout.js
- src/components/Auth/AuthLayout/customizations.js
- src/components/ContentSingle.js
- src/components/FeatureFeed/Features/HorizontalCardListFeature.js
- src/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- src/embeds/FeatureFeed.js
- src/ui-kit/Button/Button.js
- src/ui-kit/Button/Button.styles.js
[Welcome Modal Copy](https://3.basecamp.com/3926363/buckets/27088350/todos/6014002574)
[Modal Back Button styling is weird?](https://3.basecamp.com/3926363/buckets/27088350/todos/6014017385)
[Mobile Viewport: Title+Share Button should stack](https://3.basecamp.com/3926363/buckets/27088350/todos/6014107774)
[Mobile Viewport: Horizontal Padding](https://3.basecamp.com/3926363/buckets/27088350/todos/6014104275)
- Changed welcome message from "We're glad you're here..." to "Please login to continue"
- Changed padding to be less tight for smaller resolutions
- Title + share button stacks on smaller screens
- Adjusted back button caret
> 🛠 End of Cycle QA Fixes

- src/components/Auth/AuthIdentity.js
- Removed ToS and policy check
Before:
After:
> 🛠 Remove ToS + Privacy Policy check

- src/components/ContentSingle.js
- src/utils/index.js
- src/utils/parseDescriptionLinks.js
- Added function that checks if description contains a link. If so, adds an <a> tag so the user can be redirected
Before:
After:
> ⭐️ Make links clickable from description

- src/components/ContentSingle.js
- src/hooks/useContentItem.js
[Sermons has no siblings](https://3.basecamp.com/3926363/buckets/27088350/todos/6014098392/)
1. added `siblingContentItemsConnection` to useContentItem 
2. display sibling content items on `ContentSingle`
Before:
After:
> [💻 Web Embed] Sermon child not showing up

- public/index.html
- src/App.js
- src/components/ContentSingle.js
- src/components/FeatureFeed/Features/HeroListFeature.js
- src/components/FeatureFeed/Features/HorizontalCardListFeature.js
- src/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- src/components/FeatureFeed/Features/VerticalCardListFeature.js
- src/components/FeatureFeedList/FeatureFeedListGrid.js
- src/components/Modal/Modal.js
- src/components/Modal/Modal.styles.js
- src/components/Modal/index.js
- src/components/index.js
- src/embeds/FeatureFeed.js
- src/hooks/useContentItem.js
- src/index.js
- src/providers/AppProvider.js
- src/providers/BreadcrumbProvider.js
- src/providers/ModalProvider.js
- src/providers/index.js
- src/ui-kit/ShareButton/ShareButton.styles.js
- src/utils/getContentFromURL.js
- src/utils/index.js
[💻 Web Embed: Modal-Based Navigation](https://3.basecamp.com/3926363/buckets/27088350/todolists/6085433057) 
**Note 5/2:** _Currently the search trigger is not there, and no back button._
1. Created a modal component that can take in children to render
3. Created a modal provider in order to control the state of the modal, whether to show or hide, as well as to set the content of the modal
4. Added a prop to the embed to configure modal. It is set to true by default (in the initialState of the provider).
5. Content will display in modal or fullscreen depending on configuration
6. Clicking outside the modal or on the 'X' button will close the modal
https://user-images.githubusercontent.com/68402088/235788650-fd5a9999-590e-49a5-a8d1-d9133c4ed0dc.mov
> 💻 Web Embed: Modal-Based Navigation

- src/components/Breadcrumbs/Breadcrumbs.js
- src/components/ContentSingle.js
- src/components/FeatureFeed/Features/HeroListFeature.js
- src/components/FeatureFeed/Features/HorizontalCardListFeature.js
- src/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- src/components/FeatureFeed/Features/VerticalCardListFeature.js
- src/components/FeatureFeedList/FeatureFeedListGrid.js
- src/components/Modal/Modal.js
- src/embeds/FeatureFeed.js
- src/hooks/useContentItem.js
- src/providers/BreadcrumbProvider.js
- src/providers/ModalProvider.js
**Basecamp Scope**
[[💻 Web Embed: Modal-Based Navigation](https://3.basecamp.com/3926363/buckets/27088350/todolists/6085433057)
](https://3.basecamp.com/3926363/buckets/27088350/todos/6093659671)
**What was done?**
Fix breadcrumbs to track browser history correctly
Fix a bug when removing breadcrumbs
Fix option chaining bug in Hero Feature
Fx dropRight util to drop everything to the right when user clicks on a breadcrumb based on total length of the breadcrumbs
Lots of integration fixes to get this to work with the new modal based navigation
**How to test**
Navigate around the app and make sure breadcrumbs, urls, etc all update and load correctly when using the breadcrumbs, keyboard, or browser navigate to get around.
https://user-images.githubusercontent.com/2528817/235966185-b484509f-43c …
> Breadcrumbs v2

- src/components/Modal/Modal.js
- src/components/Modal/Modal.styles.js
[Make modal-based nav full-screen](https://3.basecamp.com/3926363/buckets/27088350/todos/6117632803)
- Changed modal to be fullscreen
https://user-images.githubusercontent.com/68402088/236269409-feeeb670-036f-4ac3-9646-2070081a35e2.mov
> [💻 Web Embed] Make modal-based nav full-screen

- public/index.html
- src/App.js
- src/components/FeatureFeed/Features/HeroListFeature.js
- src/components/Modal/Modal.js
- src/hooks/useCurrentUser.js
- src/providers/AppProvider.js
- src/ui-kit/Search/Search.js
- src/ui-kit/Search/Search.styles.js
- src/ui-kit/Search/index.js
- src/ui-kit/index.js
[Search Trigger](https://3.basecamp.com/3926363/buckets/27088350/todolists/6085422251)
_Note: Church theme colors not yet defined_
1. Create Search trigger component
2. Has clickable interface: Click anywhere on the search bar should open the interface
_Note: Clicking on profile right now will open Auth, this function can be moved to the profile menu later on_
3. Has configurable text prompt depending if user is logged in. It will disappear when user clicks into search bar, or if the search bar is empty
4. Auth no longer shows right away. Users will have to use the search trigger to log in
5. Icon color theme based on church colors. If no church colors passed in, uses default colors instead
- _Recorded when no user logged in_
https://user-images.githubusercontent.com/68402088/236936619-9a9 …
> Search Trigger

- src/components/Auth/AuthIdentity.js
- src/components/Auth/AuthLayout/AuthLayout.js
- src/components/Breadcrumbs/Breadcrumbs.js
- src/components/FeatureFeed/Features/HeroListFeature.js
- src/components/FeatureFeed/Features/HorizontalCardListFeature.js
- src/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- src/components/FeatureFeed/Features/VerticalCardListFeature.js
- src/components/Profile/Profile.js
- src/components/Profile/ProfileDetails.js
- src/hooks/useCurrentUser.js
- src/hooks/useUpdateProfileFields.js
- src/ui-kit/Button/Button.js
- src/ui-kit/Button/Button.styles.js
- src/ui-kit/Input/Input.js
[Build out the Personal Details view](https://3.basecamp.com/3926363/buckets/27088350/todos/6130812005/edit?replace=true)
Added the Profiles Details component so users can now update their first and last names.
https://github.com/ApollosProject/apollos-embeds/assets/2528817/a4b35a00-adf3-4e3d-8cd9-4308e14b214d
> Profile details

- src/components/FeatureFeedList/FeatureFeedListGrid.js
- src/components/Profile/Profile.js
- src/hooks/index.js
- src/hooks/useContentItem.js
- src/hooks/useCurrentChurch.js
- src/hooks/useFeatureFeed.js
- src/providers/AppProvider.js
- src/ui-kit/ThemeProvider/ThemeProvider.js
Merge https://github.com/ApollosProject/apollos-embeds/pull/42 first
[Create church color theme definition](https://3.basecamp.com/3926363/buckets/27088350/todos/6131017266/edit?replace=true)
Fixed a few errors and warnings in the console
Added the church custom theme colors using useCurrentChurch
> Connect church theme

- package-lock.json
- package.json
- src/components/Profile/ImageUploader.js
- src/components/Profile/Profile.js
- src/components/Profile/Profile.styles.js
- src/components/Profile/canvasPreview.js
- src/components/Profile/useDebounceEffect.js
- src/hooks/index.js
- src/hooks/useCurrentUser.js
- src/hooks/useUploadProfileImage.js
- src/index.js
[+1 Add upload profile image to avatar component](https://3.basecamp.com/3926363/buckets/27088350/todos/6093796205/edit?replace=true)
Added the ability for users to update there profile image
https://github.com/ApollosProject/apollos-embeds/assets/2528817/1d23f48a-ae1a-4a1f-99c5-bb8ed1af3990
> Edit profile image

- public/index.html
- src/components/FeatureFeed/Features/HeroListFeature.js
- src/components/Profile/Profile.js
- src/components/Searchbar/Autocomplete.js
- src/components/Searchbar/Search.styles.js
- src/components/Searchbar/Searchbar.js
[🐞 Fix Ad logo background color and logo for individual churches](https://3.basecamp.com/3926363/buckets/27088350/todos/6173755837)
1. Changed colors to use base.primary
2. Cleanup logs and unused code
_Note: The logo color seemed to be working fine, so I just changed some of the icons and text to also use the colors. Can be reverted if needed_
Cedar Creek:
Bayside:
King of kings:
> Church logo

- public/index.html
- src/components/FeatureFeed/Features/ActionListFeature.js
- src/components/FeatureFeed/Features/ChipListFeature.js
- src/components/FeatureFeed/Features/ChipListFeature.styles.js
- src/components/FeatureFeed/Features/HorizontalCardListFeature.js
- src/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- src/components/FeatureFeed/Features/VerticalCardListFeature.js
- src/components/FeatureFeedList/FeatureFeedList.js
- src/components/FeatureFeedList/FeatureFeedListGrid.js
- src/hooks/useFeatureFeed.js
https://3.basecamp.com/3926363/buckets/27088350/todos/6259918359
Fixes data coming through to search test feature feed and updates components to use that data.
I setup a feature for 'What's Happening at CedarCreek' to test a single feature id that is a horizontal card list. We also now have a Search feature feed setup for Cedar Creek. Both are set up in the Admin. 
https://admin.apollos.app/cedar_creek/feeds/33b34f30-e57c-4c23-9f28-24d31959a3f4
https://admin.apollos.app/cedar_creek/feeds/5aae43e6-3526-4cd2-8dfe-771d2ce8a333
I also adjusted how we map to a feed grid list component or just a feed component by passing a view all param when someone clicks that button on a horizontal card list item.
https://github.com/ApollosProject/apollos-embeds/assets/2528817/ef137b5f-e16f-4a96-b810-b2123c44 …
> Fix empty search feature feeds

- src/components/FeatureFeed/Features/HorizontalCardListFeature.js
- src/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- src/components/FeatureFeed/Features/VerticalCardListFeature.js
- src/components/FeatureFeedList/FeatureFeedListGrid.js
[🐞 Primary Action not working correctly](https://3.basecamp.com/3926363/buckets/27088350/todos/6263835361)
1. Refactor how the `setSearchParams` part in `handlePrimaryActionPress` was written
2. Feed grid items use index for key instead of title know to prevent warnings
https://github.com/ApollosProject/apollos-embeds/assets/68402088/d2b8fbf0-9a6d-4ff9-bd6a-8f29bbe3b991
> 🐞 Primary Action not working correctly

- src/components/FeatureFeed/Features/HorizontalCardListFeature.js
- src/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- src/components/FeatureFeed/Features/VerticalCardListFeature.js
- src/components/Modal/Modal.styles.js
- src/components/Profile/Profile.js
- src/components/Profile/Profile.styles.js
- src/components/Searchbar/Search.styles.js
- src/ui-kit/Button/Button.styles.js
- src/ui-kit/ContentCard/ContentCard.js
- src/ui-kit/_config/theme.js
[Use phosphor icon for view all](https://3.basecamp.com/3926363/buckets/27088350/todos/6279058533)
[Reduce the overall padding on content single mobile](https://3.basecamp.com/3926363/buckets/27088350/todos/6279035359)
[Change promo buttons on profile menu to be high contrast version](https://3.basecamp.com/3926363/buckets/27088350/todos/6279081110)
[Remove shadow on the search bar input when dropdown is open](https://3.basecamp.com/3926363/buckets/27088350/todos/6279054972)
[Center align everything on Profile menu screen](https://3.basecamp.com/3926363/buckets/27088350/todos/6278265409)
[🐞 Change the color of the upload button or avatar placeholder](https://3.basecamp.com/3926363/buckets/27088350/todos/6273550792)
[Remove bottom horizontal scroll bar on the search …
> Styling qa

- packages/web-shared/components/Searchbar/Autocomplete.js
https://github.com/ApollosProject/apollos-embeds/assets/2528817/d696a676-9d65-45bd-b6e3-8f0bd1d472dc
> Link to url if static page

- packages/web-shared/components/FeatureFeedList/FeatureFeedList.js
- packages/web-shared/components/FeatureFeedList/FeatureFeedList.styles.js
- packages/web-shared/embeds/Search.js
- packages/web-shared/embeds/Search.styles.js
- packages/web-shared/providers/SearchProvider.js
- packages/web-shared/ui-kit/ThemeProvider/ThemeProvider.js
- web-embeds/package.json
- web-embeds/src/index.css
- web-embeds/yarn.lock
This add a bit of a delayed fade in for Search and the FeatureFeed Embeds. The current Cedar Creek site has a lot of janky loading that happens. So, I'm trying to use animations to soften the blow of a large react app loading inside of a Webflow site.
There is also another attempt at fixing the global styles for web-embeds, but also not break anything in Webflow. 
https://github.com/ApollosProject/apollos-embeds/assets/2528817/f6990bfa-7d27-462f-8c3e-e7fc75741515
> Loading states

- packages/web-shared/components/Searchbar/Searchbar.js
https://3.basecamp.com/3926363/buckets/27088350/todos/6423897838
> Change the default search text

- packages/web-shared/components/Searchbar/Search.styles.js
- packages/web-shared/ui-kit/ResourceCard/ResourceCard.js
- packages/web-shared/ui-kit/ResourceCard/ResourceCard.styles.js
Tightened all the items up a bit for the search results.
https://3.basecamp.com/3926363/buckets/27088350/todos/6423900569
> Reduce search item height

- packages/web-shared/components/Searchbar/Searchbar.js
- packages/web-shared/providers/AppProvider.js
- packages/web-shared/providers/SearchProvider.js
- web-embeds/public/index.html
- web-embeds/src/App.js
Add the ability to pass a custom prompt/placeholder to search. Requested by Liquid Church to implement their embeds and new Webflow website.
1. Fire it up locally add a `data-custom-prompt` attribute to your embed, or remove it if it is already in the index.html
2. Refresh and look at the search, it should show the custom prompt you put in your attribute
With  `data-custom-prompt`
Without  `data-custom-prompt`
Video walkthrough
https://www.loom.com/share/465fc6733c1042ca88f4ced7a889e565
> Add the ability to pass a custom prompt/placeholder to search

- packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js
- packages/web-shared/components/FeatureFeed/Features/HeroListFeature.styles.js
- packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js
- packages/web-shared/components/FeatureFeed/Features/HorizontalMediaListFeature.js
- packages/web-shared/ui-kit/ContentCard/ContentCard.js
- packages/web-shared/ui-kit/ContentCard/ContentCard.styles.js
- packages/web-shared/ui-kit/MediaItem/MediaItem.js
- packages/web-shared/ui-kit/_config/theme.js
Initial we set up the hero feature to match the mobile version to give us the ability to test feature feeds through the admin. However, as liquid church came on as a client. They requested a more feature rich web-embeds which made it so we needed to update the design and layout of this feature. This was captured in the designs before we had a product Roadmap, so it was overlooked as a priority. So, now it is being working on in cycle as an F&I to be able to deliver for the client. 
The Vercel testing link we be set up to use the Liquid Feature that was referenced in the request.
Extra fixes:
1. I updated the horizontal features to align breakpoints with the hero feature
2. I updated the title of Content Cards to allow for two lines before truncating
3. I fixed a issue with the carousel …
> Improve hero list feature

- .github/pull_request_template.md
Updates the PR template to match the flow described [here](https://3.basecamp.com/3926363/buckets/27088350/messages/6705670071)
1. hmmmm 🤔 
2. Maybe make a pr once this is merged?
> chore: Update PR Template

- .github/CODEOWNERS
> chore: Marking @jordanwade as sole codeowner

- .github/CODEOWNERS
> Remove code owner

- packages/web-shared/components/FeatureFeed/Features/ScriptureFeature.js
I was trying to record a Cycle Demo and realized that there was a parsing error.
Fix the regex and adjust the logic so that scripture references with a single chapter and a range of verses parses correctly
1. Start up Admin and Web Embeds (micro-service)
2. Check out http://localhost:3000/apollos_demo/content/8aa3cff4-5054-4464-b1dc-e2e31c5adf1d
3. Check out http://localhost:3001/?id=UniversalContentItem-8aa3cff4-5054-4464-b1dc-e2e31c5adf1d (port may be different for you)
| --- | --- |
| <img width="1033" alt="before" src="https://github.com/ApollosProject/apollos-embeds/assets/72768221/ca1c7cc6-9010-471e-81d5-aad26246f5a0"> | <img width="971" alt="after" src="https://github.com/ApollosProject/apollos-embeds/assets/72768221/cac2c921-9134-4e73-8af9-67a025fa392e"> |
> fix: better regex and logic for figuring out chapter or verse range

- packages/web-shared/components/ContentChannel.js
- packages/web-shared/components/ContentSeriesSingle.js
- packages/web-shared/components/ContentSingle.js
- packages/web-shared/components/Wordmark/Wordmark.js
- packages/web-shared/embeds/FeatureFeed.js
- packages/web-shared/ui-kit/ButtonGroup/ButtonGroup.js
- packages/web-shared/ui-kit/ContentCard/ContentCard.js
- packages/web-shared/ui-kit/ResourceCard/ResourceCard.js
- packages/web-shared/ui-kit/ShareButton/ShareButton.js
Adds additional class names to make custom styling for web embeds easier. 
1.[ Open the preview](https://vercel.com/apollos-embeds/apollos-web-embeds/Ej3cpGM3uHcTmeufh35Ctw1qnGMT), click around :)
> chore: Additional class names

- micro-service/package.json
- yarn.lock
> fix next build

- packages/web-shared/components/AddToCalendar/AddToCalendar.js
- packages/web-shared/components/FeatureFeed/Features/EventBlockFeature.js
- packages/web-shared/hooks/useFeatureFeed.js
Closes #205 
Added ICS url from query to link
1. Open Event Page and click on apple event adding feature
2.
https://github.com/ApollosProject/apollos-embeds/assets/138706838/62c8798b-be02-447f-9481-a136f345f45a
> Main event blocks should use cluster generated ics

- packages/web-shared/providers/AnalyticsProvider.js
Web Embeds analytics does not include church slug.
Include church slug. 
1. Change the tracking libraries to include `{ track: console.log }`
2. Boot up `web-embeds` and click on any content item
> fix: Church not being logged

- packages/web-shared/components/Searchbar/Searchbar.js
Reverts ApollosProject/apollos-embeds#238
> Revert "Apo 1022 seacoast search bar alignment"

- packages/web-shared/components/Searchbar/Searchbar.js
Reverts ApollosProject/apollos-embeds#239
> Revert "Revert "Apo 1022 seacoast search bar alignment""

- packages/web-shared/components/Searchbar/Autocomplete.js
Closes #251
Include events
search for "quiz" with river valley
https://github.com/user-attachments/assets/3b40335d-5200-4ce1-a2f5-4659b61b205e
> adds events to search results

- packages/web-shared/components/VideoPlayer/VideoPlayer.js
> fix HLS videos

- packages/web-shared/components/EventCalendar/EventCalendar.js
- packages/web-shared/components/EventCalendar/index.js
- packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js
- packages/web-shared/hooks/useFeatureFeed.js
- packages/web-shared/ui-kit/ContentCard/ContentCard.js
Closes APO-1446
1.
2.
https://github.com/user-attachments/assets/53239596-507f-4806-ab8c-a63775d22d47
https://github.com/user-attachments/assets/2b559a77-be7e-4943-a184-b0ccae13548e
> (Liquid) Embed Styling Incorrect APO-1446

- packages/web-shared/components/VideoPlayer/VideoPlayer.js
Closes APO-1572
1.
2.
https://github.com/user-attachments/assets/d7371ebf-09d7-4681-b268-d1bc757a6735
> Allow For Two Videos With YouTube As Primary APO-1572

- packages/web-shared/components/VideoPlayer/VideoPlayer.js
This pull request includes changes to the `VideoPlayer` component in the `packages/web-shared` directory. The changes focus on improving the way video sources are identified and handled, particularly for HLS and YouTube videos.
* [`packages/web-shared/components/VideoPlayer/VideoPlayer.js`](diffhunk://#diff-d7412c3d7876a3cea451786f746381e19896808e8cc5345893602b6dab8928a0L38-R44): Modified the logic to separately identify HLS and YouTube video sources before determining the primary video source to use.
* [`packages/web-shared/components/VideoPlayer/VideoPlayer.js`](diffhunk://#diff-d7412c3d7876a3cea451786f746381e19896808e8cc5345893602b6dab8928a0L246-R249): Simplified the configuration setup for the video player by maintaining the existing logic for YouTube sources and adding a specific HLS …
> fixes youtube thing
