src/ui-kit/ResourceCard/ResourceCard.js, src/ui-kit/ResourceCard/ResourceCard.styles.js, src/ui-kit/ResourceCard/index.js, src/ui-kit/index.js
[⭐️ Resources Card](https://3.basecamp.com/3926363/buckets/27088350/todos/5882000915)
Note: Had trouble with the styling on smaller resolutions, added a comment in the code: https://github.com/ApollosProject/apollos-embeds/blob/4631258f7b17c182b972f852f5dc577cbc53596d/src/ui-kit/ResourceCard/ResourceCard.styles.js#L46
1. Created Resource Card component
2. Users can pass in a `title`, `subtitle`, `leadingIcon`, `tailingIcon`, and `node`
3. `leadingIcon` can be passed an image source URI to display. If the prop is not an image, then it will display whatever is passed in. If undefined, the leadingIcon will default to the paperclip icon
4. `tailingIcon` will display whatever is passed in. If undefined, the leadingIcon will default to the arrow icon
5. `node` is passed in if the user wants to …
=> ⭐️ Resources Card

src/components/Auth/AuthIdentity.js, src/components/Auth/AuthLayout/AuthLayout.js
Quick fix to toggle between login and sign-up screens. Also, added a back button to the confirm screen just in case a user puts in the wrong email.
=> Fix create account and log in links in AuthIdentity

src/ui-kit/Input/Input.styles.js
[🧹 Clean up login styling](https://3.basecamp.com/3926363/buckets/27088350/todos/5999023276)
What was done:
- Changed padding
Before:
After:
=> 🧹 Clean up login input styling

src/components/FeatureFeed/Features/HorizontalCardListFeature.js, src/components/FeatureFeed/Features/VerticalCardListFeature.js, src/components/FeatureFeed/Features/VerticalCardListFeature.styles.js, src/components/FeatureFeedList/FeatureFeedListGrid.js, src/ui-kit/ContentCard/ContentCard.js
[⭐️ Make Content Cards more consistent in size](https://3.basecamp.com/3926363/buckets/27088350/todos/5978155783)
1. Refactor horizontal list and feature feed grid to be more responsive
2. Refactor content card to use ellipses to truncate text after one line in order to keep card heights more consistent (this can be reverted if it doesn't fit the intended design)
Before:
https://user-images.githubusercontent.com/68402088/228653224-4faff404-5317-4495-a211-0d57b08e8306.mov
After:
https://user-images.githubusercontent.com/68402088/228652948-fb142b2d-7fa6-46a3-9778-a3a2ef4501b1.mov
=> ⭐️ Make Content Cards more consistent in size

src/components/FeatureFeed/Features/HeroListFeature.js
[⭐️ Limit height of content in HeroCardList](https://3.basecamp.com/3926363/buckets/27088350/todos/5978159937)
1. Add a maximum height to the image used in hero
2. will center the image in cases where images are larger than maximum height (similar to content cards)
3. buttons will flex to column on smaller resolution  in order to prevent cutoff
Before:
https://user-images.githubusercontent.com/68402088/228948567-9bfa0c64-7061-4396-8e1e-8efaa3e1b69f.mov
After:
https://user-images.githubusercontent.com/68402088/228948558-746ab60d-46a8-4d88-a5bd-b3f8dc0baa02.mov
=> ⭐️ Limit height of content in HeroCardList

src/components/FeatureFeed/Features/HorizontalCardListFeature.js
[⭐️ Add logic to Continue watching section](https://3.basecamp.com/3926363/buckets/27088350/todos/5978180888)
Note: This is open to input on design & necessity 
1. Added logic for displaying "no content" messages
=> ⭐️ Add logic to Continue watching section

src/components/FeatureFeed/Features/HorizontalCardListFeature.js, src/components/FeatureFeed/Features/HorizontalMediaListFeature.js, src/hooks/useTabFeed.js, src/ui-kit/ButtonGroup/ButtonGroup.js, src/ui-kit/ButtonGroup/ButtonGroup.styles.js
- Quick fix to match HorizontalMediaListFeature.js with HorizontalCardListFeature.js
- HorizontalMediaListFeature features should not show up anymore when there are no items to render.
- Add disabled functionality to custom carousel arrows
- Attempts to fix a feature loading issue in production that I think is related to the carousel package. 
- Fix view all functionality on HorizontalMediaListFeature
=> 🪲 Fix/more bugs

src/components/FeatureFeed/Feed.js, src/components/LivestreamSingle.js, src/components/VideoPlayer/VideoPlayer.js, src/hooks/index.js, src/hooks/useLivestreamStatus.js, src/ui-kit/MediaItem/LiveChip.js, src/ui-kit/MediaItem/MediaItem.js, src/ui-kit/MediaItem/MediaItem.styles.js
Updates the `useLivestreamIsActive` hook to be `useLivestreamStatus` and return a status of `isLive` or `comingUp`. This makes it so we can have more granular control with what styles and information we show on the `LiveChip` component. In the future we will probably add actual time until the stream is live. I felt this is a good iterative step towards that functionality.
=> Return a status from the useLivestreamStatus hook

src/components/Auth/AuthDetails.js, src/ui-kit/Select/Select.js
[(Web Embeds) - Can't onboard w/ Bayside Web Embed](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6040356392)
1. Checking is now based on if the entire profile is completed rather than each individual item
2. Button is now disabled unless every item has been filled out (rather than first and last name only). This should remove partially filled out profiles from now on
3. If profile is fully complete, button should no longer be disabled.
- If you have no account/partially completed profile
- It should display inputs to fill out
- button should be disabled until everything is filled out
https://user-images.githubusercontent.com/68402088/232123103-7a13002b-07dc-447d-8fb0-8925811ddbeb.mov
- If you have completed profile
- It should display message to continue
- button …
=> (Web Embeds) - Can't onboard w/ Bayside Web Embed

src/components/Auth/AuthDetails.js
[[💻 Web Embeds] Onboarding flow to add profile information is broken.](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6049699732)
1. run complete Register hook during auth details step to set a apollos user to `TRUE` as well a get a rock id
=> [💻 Web Embeds] Onboarding flow to add profile information is broken.

src/components/Breadcrumbs/Breadcrumbs.js, src/components/ContentSingle.js, src/embeds/FeatureFeed.js, src/providers/BreadcrumbProvider.js
[Breadcrumbs not working correctly with browser back button and using keyboard `cmd left arrow`](https://3.basecamp.com/3926363/buckets/27088350/todos/6018447603)
1. Added useEffect to breadcrumb component
2. Listens for `popstate` event. Removes last item of state
3. Breadcrumb should now disappear when it's suppose to (at the root)
_Note: The breadcrumb also resets when the user goes forward as well, looking into fix for that_
Before:
https://user-images.githubusercontent.com/68402088/231886734-69cd3ab0-7f14-4ed3-baa3-d0b5c1f56a21.mov
After:
https://user-images.githubusercontent.com/68402088/231886753-693e7041-b046-44c2-b2fa-c4e3b02ae739.mov
=> 🛠 Breadcrumbs not working correctly when navigating backwards in the browser 

src/components/ContentSingle.js
[[💻 Web Embed] Fix styling for children content items](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6056739057/)
1. Fix styling on child content items for `ContentSingle`
Before:
https://user-images.githubusercontent.com/68402088/233153563-74043a39-6091-4eeb-a35d-7c5efc63c68f.mov
After:
https://user-images.githubusercontent.com/68402088/233153404-1978bd07-a26a-4b82-940c-2a2417c2a08a.mov
=> [💻 Web Embed] Fix styling for children content items

src/components/Searchbar/Autocomplete.js
[Query Result State: Page Search Results](https://3.basecamp.com/3926363/buckets/27088350/todos/6159604550/edit?replace=true)
This makes it so we are only searching church specific content in the WebPages_Global index.
=> Add facet filters to pages search

src/components/Modal/Modal.js, src/components/Searchbar/Autocomplete.js, src/components/Searchbar/Search.styles.js, src/components/Searchbar/Searchbar.js, src/ui-kit/ResourceCard/ResourceCard.js, src/ui-kit/ResourceCard/ResourceCard.styles.js
[Polish: Search Bar F&Is](https://3.basecamp.com/3926363/buckets/27088350/todos/6203786717/)
_Will handle scroll behavior in seperate branches_
1. Fix the styling to match whats in figma
2. Refactored the 'X' button to be inside the autocomplete component. Also using the 'X' will add the query to the user's recent searches
3. Refactored the caret dropdown to be inside the autocomplete component to trigger dropdown toggle
4. Changed the recent/suggested search to use the 'right caret icon' instead of the 'diagonal arrow' to match the resource cards and figma design below (can be changed back if needed)
5. add mobile responsiveness
Styling + x + caret
https://github.com/ApollosProject/apollos-embeds/assets/68402088/9be7bc5c-3ab0-4cab-be55-71736d02d578
Mobile …
=> Search bar fi

public/index.html, src/App.js, src/components/Searchbar/Autocomplete.js, src/embeds/FeatureFeed.js, src/embeds/Search.js, src/index.js, src/providers/AppProvider.js, src/providers/SearchProvider.js
[Empty Search State: Feature Feed](https://3.basecamp.com/3926363/buckets/27088350/todos/6093728369/edit?replace=true)
Adds feature feed to search and update FeatureFeed embed to use FeatureFeedProvider instead of TabFeedProvider. This PR wires up search and feature feed to work with feature feed ids. We currently don't have the actually feeds done for any church, but this proves that the functionality works. The feature id I'm using makes it look crappy but it is just for testing. Once the feeds are configured we can plug in the id and then create the last component based of the data. I think it will be a action link list or something like that. 
We will need the typename, id, and title/slug for that "feature/list of links". We should be able to use the ResourceCard component for the …
=> Feature feed refactor

public/index.html, src/components/Searchbar/Autocomplete.js, src/components/Searchbar/Search.styles.js
[Desktop Specific Behavior: Scroll to Results](https://3.basecamp.com/3926363/buckets/27088350/todos/6093749767/edit?replace=true)
[Mobile Specific Behavior: Anchor search field to top](https://3.basecamp.com/3926363/buckets/27088350/todos/6093757977/edit?replace=true)
1. When user presses enter on search bar, will scroll down to the results section (currently tagged on the Content title)
2. On mobile, new keystrokes will reset scroll to the top
3. Styling changes + no results message when no items are rendered
_Note: No completely satisfied with how the desktop behavior works with scrolling (it will scroll the browser window before scrolling the dropdown). If needed, can improve in future PR_
https://github.com/ApollosProject/apollos-embeds/assets/68402088/2141d803-dcde-4cd6-ad95-6f31059d …
=> Scroll behavior

src/components/ContentSingle.js, src/components/FeatureFeed/Features/ActionListFeature.js, src/components/FeatureFeed/Features/ButtonFeature.js, src/components/FeatureFeed/Features/ChipListFeature.js, src/components/Modal/Modal.js, src/components/Searchbar/Autocomplete.js, src/utils/parseDescriptionLinks.js
- All bug fixes here are related to functionality/UX, and are not related to/don't need changes in backend or admin.
- I will have separate PR for styling and the other functionality/UX todos
- Lots of scopes in this PR, added checklist if it helps
- Let me know if this PR fixes this basecamp scope as well, I've added some comments on the todo: [🐞 Breadcrumbs are not working correctly](https://3.basecamp.com/3926363/buckets/27088350/todos/6275249213)
- **Basecamp fixes**
- All things tracked on Basecamp are below with what was done
- **Non-Basecamp fixes**
- Reset breadcrumb state when 'x'ing out of a modal (doesn't make sense that the breadcrumbs stack once closing out modal + removes duplicates)
- Slight edit to ButtonFeature for when churches pass in a HTML button to render, which will …
=> (No Backend) Functional/UX Related QA

src/components/Logo/Logo.js, src/components/Logo/Logo.styles.js, src/components/Profile/Profile.js, src/hooks/useCurrentChurch.js
[🐞 Change the logo to the correct church logo dynamically](https://3.basecamp.com/3926363/buckets/27088350/todos/6259906908)
[🐞 Logo not working on Cedar Creek demo](https://3.basecamp.com/3926363/buckets/27088350/todos/6273532863)
1. Use current church's logo to render in profile menu
2. edit `Logo` component to accept a source, or default to apollos icon
_Cedar Creek logo below_
=> Church logo

packages/web-shared/components/Searchbar/Autocomplete.js, packages/web-shared/components/Searchbar/Search.styles.js
Before:
After:
Ignore the background on the "after", that is just a local change to see the border issue easier.
=> Fix border-radius issue on search panel

packages/web-shared/components/Breadcrumbs/Breadcrumbs.js
Changes the root breadcrumb from just "Featured" to be dynamically driven by the url.
=> Improve base breadcrumb to be driven by url

packages/web-shared/components/FeatureFeed/Features/ActionListFeature.js, packages/web-shared/components/FeatureFeed/Features/ChipListFeature.js, packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js, packages/web-shared/components/FeatureFeed/Features/HorizontalMediaListFeature.js, packages/web-shared/components/FeatureFeed/Features/VerticalCardListFeature.js, packages/web-shared/components/LivestreamSingle.js, packages/web-shared/hooks/useFeatureFeed.js
Currently, in the Admin sometimes feature feeds get setup with subtitles and not titles. This PR defaults to the title and if one isn't present it will use the subtitle.
Basecamp: https://3.basecamp.com/3926363/buckets/27088350/todos/6419832929
Relevant links:
https://newspring.apollos.church/?root=FeatureFeed-567b0865-443f-4447-8fa4-ce5db221ecf1
http://newspring.localhost:3000/?root=FeatureFeed-567b0865-443f-4447-8fa4-ce5db221ecf1
Before
After
=> Support subtitles on all features

packages/web-shared/components/Modal/Modal.js, packages/web-shared/components/Modal/Modal.styles.js, packages/web-shared/components/Profile/Profile.js, packages/web-shared/components/Profile/Profile.styles.js
[(Web) Fix modal padding issues](https://3.basecamp.com/3926363/buckets/27088350/todos/6438291134)
1. add `box-sizing: border-box;` to modal to fix padding issue
2. Fix "x" icon in modal being squished
- opening modal/auth profile should have padding all around
- when scrolling to the bottom of the page, padding from modal (hidden at the bottom of the page for animation) no longer should block content
- when resizing modal, the x button should remain circular
1. This is how the padding should now look
##
2. This is the padding at the bottom of the page that should be gone now
##
3. "X" icon after
##
4.  "X" icon before
=> (Web) Fix modal padding issues

packages/web-shared/hooks/useInteractWithNode.js, packages/web-shared/providers/AuthProvider.js
This fixes an issue when a user refreshes or changes the route of the website state is wiped out so we lost the reference to the auth token. We no longer need this check since auth is a core needed element for some features to work correctly.
Note: This also could have been fixed by adding a environment variable to the webflow app, but I don't think we should do that since it would just complicate the setup of web-embeds for customers 
https://github.com/ApollosProject/apollos-embeds/assets/2528817/aad3b9d4-05c3-4d6d-a3e0-19cfc39efcc9
=> Remove authEnabled, auth is always needed now for some features

packages/web-shared/components/Searchbar/Autocomplete.js, packages/web-shared/components/Searchbar/Search.styles.js
[(Web Micro-Service) Fix search height when there is no Search Feed id](https://3.basecamp.com/3926363/buckets/27088350/todos/6419894036)
1. added `max-height` to modal instead of set height
2. add padding to bottom of panel just to give some space for the last item 
- open search
- the panel should no longer be a set height, so if there is no feature feed, there should be no whitespace
=> (Web Micro-Service) Fix search height when there is no Search Feed id

packages/web-shared/components/FeatureFeed/Features/ButtonFeature.js
[(Web) Buttons don't work in long form content items](https://3.basecamp.com/3926363/buckets/27088350/todos/6419852102/)
1. Edit the `ButtonFeature` component to correctly take in props
- Buttons in HTML content for Content single should have working buttons
https://github.com/ApollosProject/apollos-embeds/assets/68402088/5b4825f1-a808-43e4-9d3d-9935c94d293a
=> (Web) Buttons don't work in long form content items

packages/web-shared/components/Modal/Modal.js
[(Web) Modal animation flashes on page load](https://3.basecamp.com/3926363/buckets/27088350/todos/6464477825/edit?replace=true)
1. Have the `ModalContainer`, which has a pure white background, not be rendered unless there is content.
2. This should make it so that the animation does not appear visually.
1. refresh page, there should be no animation flash
https://github.com/ApollosProject/apollos-embeds/assets/68402088/3a7db7fe-5481-42ba-9ff8-b9b7c3a8f5a6
https://github.com/ApollosProject/apollos-embeds/assets/68402088/ba27b05e-2a14-4adf-8e5b-188c931836e0
=> (Web) Modal animation flashes on page load

packages/web-shared/components/Profile/Profile.js
[(Web) Avatar Placeholder and adding a image icon doesn't overlap correctly](https://3.basecamp.com/3926363/buckets/27088350/todos/6455343544)
1. Make Avatar Placeholder image bigger and give it negative margins
2. Negative margins since svg has padding, so increasing size alone makes the gap larger
1. Go to profile and see that camera icon is overlapping avatar placeholder
Before:
After:
Comparison to with image:
=> (Web) Avatar Placeholder and adding a image icon doesn't overlap correctly

packages/web-shared/components/ContentSingle.js
[(Web) Reduce the display size of images on the Content Single](https://3.basecamp.com/3926363/buckets/27088350/todos/6459537200)
1. reduce image width on larger screens + added background color to (according to chatGPT): "mitigate the visual impact of stretching the image while maintaining a cohesive design"
2. Added max width of 750px to images (might not be necessary when higher res pictures are uploaded)
_Note: This probably can be run by a designer as well_
1. Go to any content with image, should have responsiveness as shown below
https://github.com/ApollosProject/apollos-embeds/assets/68402088/0e249309-84c7-4510-bd5b-65d51ed9874c
Before (takes up entire width):
=> (Web) Reduce the display size of images on the Content Single

micro-service/package.json, packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js, packages/web-shared/hooks/useFeatureFeed.js, packages/web-shared/hooks/useTabFeed.js, web-embeds/package.json
This PR adds support for the hero feature, the app was just missing the query in the hook. I also, fixed a small bug where a button was rendering without data and updated our start script to be `yarn dev` to match engineering standards recently defined.
Before:
After:
=> Support hero feature

packages/web-shared/hooks/useFeatureFeed.js
Adds HorizontalMediaListFeature to the feature feed hook so we support media items and live items.
=> Support HorizontalMediaListFeature and live items

packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js, packages/web-shared/components/FeatureFeed/Features/HorizontalMediaListFeature.js, packages/web-shared/components/FeatureFeed/Features/VerticalCardListFeature.js
[(Web) View all showing both modal and web view](https://3.basecamp.com/3926363/buckets/27088350/todos/6438871997)
1. Update `handlePrimaryActionPress` in `HorizontalCardListFeature` and `HorizontalMediaListFeature` to add viewall action to url depending on if `state.modal` is true or false
1. Go to any Horizontal List Feature that has a viewall button
2. When modal="true", the modal should show the modal with the FeatureFeedGridList, and you shouldn't see it render in the background
3. When modal="false", it should have the same function as before
Before (can see FeatureFeed change to grid in the background as the modal slides up):
https://github.com/ApollosProject/apollos-embeds/assets/68402088/859904a3-100a-4164-b96d-b9e1449229cd
After: …
=> (Web) View all showing both modal and web view

packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js
[(Web) HeroListFeature not rendering correctly](https://3.basecamp.com/3926363/buckets/27088350/todos/6499872460)
1. Fix Typo in code
1. Open feed with HeroListFeature, should no longer show the code
=> (Web) HeroListFeature not rendering correctly

packages/web-shared/components/FeatureFeed/Features/ActionListFeature.styles.js, packages/web-shared/ui-kit/ResourceCard/ResourceCard.js, packages/web-shared/ui-kit/ResourceCard/ResourceCard.styles.js
[(Web) Action List feature not rendering correctly](https://3.basecamp.com/3926363/buckets/27088350/todos/6419870616)
1. Update styling on Resource card and Action Item to render properly
1. Hover over an ActionList item to see changes
=> (Web) Action List feature not rendering correctly

packages/web-shared/components/Searchbar/Searchbar.js
[(Web) Search placeholder text is getting cut off](https://3.basecamp.com/3926363/buckets/27088350/todos/6496610157)
1. Have width cutoff for ellipses be shorter only for mobile resolution, and larger for desktop sizes to prevent early cutoffs
1. Resize window screen. The cutoff for the search placeholder text should make more sense
https://github.com/ApollosProject/apollos-embeds/assets/68402088/bb78ba7d-6b47-400d-8fec-5f852bdbf5b6
=> (Web) Search placeholder text is getting cut off

packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js
[(Web) Hero List Feature erroring out from null values](https://3.basecamp.com/3926363/buckets/27088350/todos/6509857115)
1. Have `props?.feature?.primaryAction?.relatedNode` be checked for if it is a falsy value rather than just null, as it will try and render a button when `undefined` is returned
2. Add optional chaining to title to avoid erroring out
1. Used this feature feed to check:
```
<div
data-type="FeatureFeed"
data-church="apollos_demo"
data-feature-feed="FeatureFeed:3040b753-9462-4705-ba5e-4a4aad93325b"
data-modal="true"
class="apollos-widget"
></div>
```
=> (Web) Hero List Feature erroring out from null values

packages/web-shared/ui-kit/ButtonGroup/ButtonGroup.styles.js
The goal of this adjustment is to add a little bit of flexibility to our carousel arrow buttons to look ok on more than just white backgrounds. This just the first step in making our web-embeds more flexible in regards to theming. It adjusts the color and adds a little bit of transparency.
https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6675487050
1. Open up the Vercel preview and make sure the carousel arrows look good on a white background and "Ok" on other background colors.
https://github.com/ApollosProject/apollos-embeds/assets/2528817/a117cb7c-263e-422f-bfb2-5bc59b72c34c
=> Add transparency to buttonGroup buttons

packages/web-shared/ui-kit/Longform/Longform.styles.js
Quick fix that updates the styles of the anchor tags in in the longform component. It now uses the brand action color with no underline.
1. Check out the anchor links here and make sure they look good. 
https://apollos-web-embeds-git-fix-longform-ancho-1a0532-apollos-embeds.vercel.app/?id=UniversalContentItem-a38d9aa6-6a51-48ed-9120-d22374fc38c8
=> Update anchor tags to use brand color with no underline

packages/web-shared/components/Searchbar/Autocomplete.js
User feedback stated that search sections were confusing and adding section headers would help clarify what each section was.
Also, went ahead and fixed this issue while I was in the autocomplete file. https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6655702888
This PR adds "Trending Searches" and "Search History" titles to the Algolia search sections. 
When a user hits enter on the keyboard the value is added to the search history and set as the query value.
1. Open up the search functionality
2. With nothing in search a user should see the title "Trending Searches", once they type something the "autocomplete" Algolia functionality takes over and that header is hidden.
3. If a user has search history they will now see a section header above those items
4.  One extra item …
=> Feat search section headers and hitting enter on keyboard

packages/web-shared/components/ContentSeriesSingle.js, packages/web-shared/components/ContentSingle.js, packages/web-shared/components/InformationalContentSingle.js, packages/web-shared/components/LivestreamSingle.js, packages/web-shared/embeds/FeatureFeed.js, packages/web-shared/embeds/Search.js, packages/web-shared/hooks/useContentItem.js
Liquid requested layout changes to web-embeds for their series content.
I adjusted the web-embeds series layout and updated some configuration of their app to accommodate their requests, while not straying away from what is best for the product.
1. Check out the Spartan Faith Series. The hero has a new layout and the child items are content cards.
https://apollos-web-embeds-git-fix-series-ui-apollos-embeds.vercel.app/?id=ContentSeriesContentItem-ed5f1375-faa7-4e33-9bfe-028f25c5ac57
2. Check out one of the items in the Spartan Faith Series. The child items are present now and the items are content cards. 
Note: To get the child/sibling items to show up I had to update the ROCK.CONFIG in Retool for Liquid and then run a backfill on the Rock content dag.
| --- | --- |
| …
=> fix: series UI

packages/web-shared/components/ContentSingle.js, packages/web-shared/components/InformationalContentSingle.js, packages/web-shared/components/LivestreamSingle.js, packages/web-shared/components/VideoPlayer/VideoPlayer.js, packages/web-shared/hooks/useContentItem.js
Publish dates are not relevant to content items and we don't have them on mobile. Customers are sharing feedback that the dates are not helpful and are launch blocking if they are not removed.
Remove dates from content items
1. https://apollos-web-embeds-git-remove-dates-conte-fe8317-apollos-embeds.vercel.app/?id=UniversalContentItem-b7896d20-34dc-45a1-9739-e8e4a7793a73 Dates are removed
| --- | --- |
|<img width="1334" alt="image" src="https://github.com/ApollosProject/apollos-embeds/assets/2528817/e1587a2c-46f4-4b17-bee5-e0d5ca20c1f9">|<img width="1335" alt="image" src="https://github.com/ApollosProject/apollos-embeds/assets/2528817/f5dedcf1-7fa2-4f63-b5d1-ac2445100ad8">|
=> Remove publish date from content items

packages/web-shared/components/ContentSingle.js, packages/web-shared/components/Searchbar/Autocomplete.js
There was confusion around what the search titles were for 'pages' and 'content' so this PR removes those. But that also meant that we needed to update "No results found" to only so up once instead of twice. One for each index or collection of results coming from Algolia
1. Play around with search and make sure the page and content results display in a pleasing way and make sure the "No results found" only shows up once and when there are no results.
2. Also check the performance of the useEffect, I'm not sure if that is ok. There might be a better way to check for any results coming back.
| ---| --- |
|<img width="1104" alt="Xnapper-2023-11-29-15 52 24" src="https://github.com/ApollosProject/apollos-embeds/assets/2528817/edaf1280-ed16-4953-9b4e-ee8b212c475b"> |<img …
=> Remove pages content titles and update "No results Found"

micro-service/package.json, micro-service/yarn.lock, packages/web-shared/package.json
Micro-service dependency issue with tldts
Fixes the package.jsons to account for tldts package.
1.Vercel deploy should pass for micro-service
N/A
=> fix tldts dependency

packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js
https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6797509823
Add breadcrumb functionality to the hero feature `handleActionPress`
1. Click on an action item in a hero feature list it should have breadcrumbs
| --- | --- |
|<img width="1012" alt="image" src="https://github.com/ApollosProject/apollos-embeds/assets/2528817/8c78a4eb-8b4d-4d84-b23a-23e98370706e">|<img width="1061" alt="image" src="https://github.com/ApollosProject/apollos-embeds/assets/2528817/01e66333-ddc2-4baf-8073-4bdd648fbec0">|
=> Update handleActionPress in hero feature to handle breadcrumbs

packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js, packages/web-shared/components/FeatureFeed/Features/HeroListFeature.styles.js, packages/web-shared/ui-kit/Typography/_typeStyles.js
https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6811682830
Match the hero card style to designs.
Improved responsiveness and typography for titles and summaries.
1. Check out a hero feature on any screen size. It should look pleasing to the eye.
| --- | --- |
| <img width="1220" alt="image" src="https://github.com/ApollosProject/apollos-embeds/assets/2528817/eba27d12-dc71-4ad0-8374-ec65a7c86c90">| <img width="1226" alt="image" src="https://github.com/ApollosProject/apollos-embeds/assets/2528817/7924a872-e152-43a2-a594-1184805d1df6"> |
|<img width="781" alt="image" src="https://github.com/ApollosProject/apollos-embeds/assets/2528817/84157741-314c-4e63-9179-47fcb516819f">|<img width="791" alt="image" …
=> Improve HeroList typography styles

packages/web-shared/components/Modal/Modal.js
issue - https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6801492005
fix scroll issue in mobile view 
1. Open web page in mobile browser 
2. Select one content item and scroll up and down 
https://github.com/ApollosProject/apollos-embeds/assets/28708210/d2b696d5-43a2-481a-89fe-211b71e4952d
=> fix: content single item on mobile doesnt fill the full height on mobile

packages/web-shared/components/Logo/Logo.js, packages/web-shared/components/Modal/Modal.js
issue - https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6816432407
Add church logo above search bar 
1. Web embeds home page -> select a content item
http://localhost:3000/?id=internship-TWVkaWFDb250ZW50SXRlbS0zZjFiN2RhOC0yNzJiLTRiMmEtYTZhMy00ZWJjMzVlOTRkNjg%3D
=> fix: add church logo above search bar

packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js, packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js, packages/web-shared/ui-kit/ContentCard/ContentCard.js
[(Web)(Liquid) Remove Top Featured Card on Blog Page](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6902381512)
Liquid wants the hero card feature but without the top feature card
Convert `HorizontalCardListFeature` to satisfy this need. When `HorizontalCardListFeature` is given a `primaryAction` and has 2 cards or less, then it will be formatted similar to how it is down on the `HeroCardFeature`.
If no `primaryAction`, or has 3+ cards, it will render as normal with a `Carousel` 
1. Navigate to a feed with `HorizontalCardListFeature` with `primaryAction`
2. Might to adjust the code to use only 2 cards if there isn't a feature that meets the exact requirements
3. Should work as it normally does with the `HeroCardFeature` …
=> (Web)(Liquid) Remove Top Featured Card on Blog Page

packages/web-shared/components/Modal/Modal.styles.js
[(Web) Single Page Embeds Cutting Off Bottom of Modal](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6865448645)
**_NOTE: Wasn't sure how to test, nor how to diagnose the problem.  Chrome, safari, and the phone's default browser all produced different bugs, although all related to the modal. The bug were also not consistently happening (mainly the bug where the page behind the modal is being scrolled)._** 
Based on testing the site and this [stackoverflow thread](https://stackoverflow.com/questions/37112218/css3-100vh-not-constant-in-mobile-browser), the issues seem to be caused by how browsers on mobile calculate view-width and view-height. By setting a fixed 100% height, it should (in theory) avoid trying to dynamically changing the height , and just take up the …
=> (Web) Single Page Embeds Cutting Off Bottom of Modal

packages/web-shared/components/ContentChannel.js, packages/web-shared/components/ContentSeriesSingle.js, packages/web-shared/components/ContentSingle.js, packages/web-shared/components/FeatureFeed/Features/HeroListFeature.styles.js, packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js, packages/web-shared/components/FeatureFeed/Features/HorizontalMediaListFeature.js, packages/web-shared/components/FeatureFeed/Features/VerticalCardListFeature.styles.js, packages/web-shared/components/FeatureFeedList/FeatureFeedListGrid.js, packages/web-shared/components/InformationalContentSingle.js, packages/web-shared/components/LivestreamSingle.js
[(Web) Increase Vertical Padding Between Cards Sections](https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6797583038)
Add more vertical padding (3-3.5x the length of the horizontal padding) to all components that use `display: grid` to render a collection of cards
1. Navigate to any feed with View all, or any content item using a grid
2. Grid should have more vertical space between rows
Before: 
After:
https://github.com/ApollosProject/apollos-embeds/assets/68402088/0687fa4e-42b8-4248-be02-ab661f783240
=> (Web) Increase Vertical Padding Between Cards Sections

packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js
Issue - https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6856937764
not adding breadcrumb if empty title
2. http://localhost:3000/?id=html-feature-test-VW5pdmVyc2FsQ29udGVudEl0ZW0tMTU0MzczYzYtMDFkMy00NDM5LWE1YTUtMjY5NjcxYzIwYWJk
=> fix: dont add a breadcrumb if a title isnt present.

packages/web-shared/embeds/FeatureFeed.js, packages/web-shared/embeds/Search.js
https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6950727046
Add import for series single to embeds.
1. http://bayside.localhost:3000/?id=romans-Q29udGVudFNlcmllc0NvbnRlbnRJdGVtLTNiN2U5Y2FkLTY1NWMtNDk2Ni04MjM4LTBkOTkzNTliM2NmNg%3D%3D
2. http://crossroads-tv.localhost:3000/?id=nehemiah-how-to-make-your-vision-a-reality-Q29udGVudFNlcmllc0NvbnRlbnRJdGVtLWFlNjNlY2Q4LTlkMzMtNGY1My1hNzAyLThmMWJhNDhkNmJmOQ%3D%3D
=> Fix: add ContentSeriesSingle to imports for feature embeds

packages/web-shared/components/Modal/Modal.js, packages/web-shared/components/Modal/Modal.styles.js, packages/web-shared/components/Wordmark/Wordmark.js, packages/web-shared/components/Wordmark/Wordmark.styles.js, packages/web-shared/components/Wordmark/index.js, packages/web-shared/hooks/useCurrentChurch.js
[Liquid wants to use the Wordmark for their content modals.](https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/6966818760) Makes sense to me, approved by @conrad-vanl 
Pull in the wordmark from the API, and then use it instead of the modal 
1. Open the test page
2. Open an item modal.
=> Use wordmark instead of logo inside the modal

packages/web-shared/ui-kit/Button/Button.styles.js
Button styling doesn't match mobile
Add margin around buttons to match mobile
1. Nav to [this link](http://localhost:3000/?id=UniversalContentItem-8aa3cff4-5054-4464-b1dc-e2e31c5adf1d)
2. See buttons properly spaced out
| --- | --- |
| ![Screenshot 2024-01-25 at 12 45 28 PM](https://github.com/ApollosProject/apollos-embeds/assets/72768221/dac83f01-b087-4b5e-8cc1-48ba86791d24) | ![Screenshot 2024-01-25 at 12 45 18 PM](https://github.com/ApollosProject/apollos-embeds/assets/72768221/0682eeec-9558-4032-bcd5-6a6117e3acec) |
=> chore(button feature): better styling of buttons to match mobile

packages/web-shared/components/ContentSingle.js, packages/web-shared/components/ContentSingle.styles.js, packages/web-shared/hooks/useContentItem.js
Liquid wants to show series data in web embeds. 
https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/6966844981
Render a hero-like car showing series data, if there's a series attached.
1. Start the `micro-service` project
2. [Visit this item! ](http://localhost:3000/?id=psalm-8-VW5pdmVyc2FsQ29udGVudEl0ZW0tNDMwNDFmZmEtNzI1OC00OTFkLTk3ZTQtNzVmNDkyOTFmYmY0)
=> feat: Support for Series/Parent items on Web Embeds

packages/web-shared/components/Searchbar/Autocomplete.js, packages/web-shared/components/Searchbar/Search.styles.js, packages/web-shared/components/Searchbar/SearchResults.js, packages/web-shared/components/Searchbar/Searchbar.js, web-embeds/public/index.html
With the search modal open, it was possible to scroll on the page itself instead of in the modal alone. 
This was a complex issue to solve. The results list was nested inside of the search input, meaning that it's rendering was technically an `overflow` of the search input. 
To resolve this, I moved the result list outside of the search input, meaning that it properly captured scroll events instead of letting them pass through.
In order to move the result list, I had to move break apart the `Autocomplete` component, hence the large number of lines changed. 
1. I made a mess of `index.html` to demonstrate the issue. I'll roll it back after you test, if you want :) 
2. I recommend using `ngrok` to test on your phone as well.
=> fix: Stop double scroll issue

packages/web-shared/components/Modal/Modal.js, packages/web-shared/providers/AppProvider.js, web-embeds/public/index.html
https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/6979824029
Make sure, when navigating, that we are sent to the top of the change when moving between content items. We do this by scrolling the modal to the top every time the modal content changes. 
1. Open up any feed.
2. Tap on any item that's a series
3. Tap on any of the children / sibling items.
This may work for you on `web-embeds`. 
http://localhost:3001/?id=jesus-gen-z-TWVkaWFDb250ZW50SXRlbS0zZTI5ZWRiZC05NGU0LTQxZDgtODdjOC1iNzdkYmVmN2U2ZWY%3D
https://github.com/ApollosProject/apollos-embeds/assets/1637694/be04ef3f-42f6-45b5-a72c-52a172d38eb1
=> fix: Ensure scroll to top on content change

packages/web-shared/components/Searchbar/Autocomplete.js
issue - https://3.basecamp.com/3926363/buckets/27088350/card_tables/cards/6948796088
Fix navigation on algolia search
1. set configuration to search
2. select item in search result using keyboard
3. check for correct navigation
https://github.com/ApollosProject/apollos-embeds/assets/28708210/5d06f24b-d638-477b-960e-1f31419b64e4
=> fix: search not redirecting with keyboard input

packages/web-shared/components/ContentSingle.js, packages/web-shared/hooks/useContentItem.js, packages/web-shared/hooks/useFeatureFeed.js, web-embeds/public/index.html
We should render any features we support on a content item, not just features specifically queried for by the content item query. 
Provides support for: https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/6979833101
Use the featureFeed hook to query for a content item's features, rather than relying on a subquery of `contentItem` 
1. start web embeds
2. visit [this item](http://localhost:3000/?id=a-fresh-anointing-TWVkaWFDb250ZW50SXRlbS0wZjYwYmJiMy1mNWRlLTRjODMtYjk2MS1kOTg2NDM2NWYwMDk%3D)
3. You will see an action bar feature at the bottom
=> feat: Render a full feed on content items. 

packages/web-shared/components/Breadcrumbs/Breadcrumbs.js, packages/web-shared/components/ContentSingle.js, packages/web-shared/components/Modal/Modal.js, packages/web-shared/ui-kit/ResourceCard/ResourceCard.js, packages/web-shared/ui-kit/ResourceCard/ResourceCard.styles.js
https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/7009918938
https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/7010425769
- Fixed search bar width, so it's no longer wider than content.
- Fixed the ActionList feature so it no longer truncates text too early
- Fixed margin around modal header
For testing the search bar width, you can click on any item on desktop. Here's an example:
https://apollos-web-embeds-git-cleanup-header-apollos-embeds.vercel.app/?id=in-training-for-reigning-TWVkaWFDb250ZW50SXRlbS1kODI0Yjg0ZS00MDFkLTQ0NzAtOGFlNi1mYjU3Y2U4NWUwMmI%3D
For testing the action list, click on the search bar in mobile view :)
=> fix: Misc style fixes (for Liquid)

packages/web-shared/components/FeatureFeed/Features/ScriptureFeature.js, packages/web-shared/ui-kit/Longform/Longform.styles.js
Some scripture features are bombing out in `web-embeds` but not in mobile/admin
- Adjust the logic of the scripture parsing in `web-embeds`
- Also, it became apparent that there were some styling differences for HtmlFeatures. This was an easy fix, so I just threw it on this PR.
1. Start the `micro-service` by `yarn dev` in the `/micro-service` folder
2. Nav to http://localhost:3000/?id=UniversalContentItem-8aa3cff4-5054-4464-b1dc-e2e31c5adf1d
3. See 4 example ScriptureFeatures working correctly
4. If you want to verify on the mobile app, use Apollos Demo, head to the Explore tab, check out the last feature and tap on Psalm 100 Devotional
| Before |
| --- |
| ![Screenshot 2024-01-30 at 5 13 45 PM](https://github.com/ApollosProject/apollos-embeds/assets/72768221/b12c797b-ea7a-4d16-bcaa-e1d2b …
=> chore: update regex for more valid scripture feature references

packages/web-shared/components/Modal/Modal.js
Logo is too wide on small screens.
Make logo narrower on small screens.
http://localhost:3000/?id=in-training-for-reigning-TWVkaWFDb250ZW50SXRlbS1kODI0Yjg0ZS00MDFkLTQ0NzAtOGFlNi1mYjU3Y2U4NWUwMmI%3D
=> fix: Make logo narrower on small screens

packages/web-shared/components/ContentSingle.js
The feature feed on WebEmbeds is currently below the content/parent item section. 
https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/6979833101
Move it above the parent
http://localhost:3000/?id=in-training-for-reigning-TWVkaWFDb250ZW50SXRlbS1kODI0Yjg0ZS00MDFkLTQ0NzAtOGFlNi1mYjU3Y2U4NWUwMmI%3D
=> chore: Move feature feed above parent child card

packages/web-shared/components/ContentSingle.js, packages/web-shared/hooks/useContentItem.js, packages/web-shared/ui-kit/ContentCard/ContentCard.js
Two issues resolved here: 
- Spacing on card sibling/child items is too loosy-goosy
- Liquid wants to show an item's parent on the parent/sibling view.
- Tighten spacing on sibling/child items.
- Show an item's parent on the sibling/parent view. 
http://localhost:3000/?id=facing-your-saul-TWVkaWFDb250ZW50SXRlbS0wNzgwMWQ0Ni1iYWE4LTQ0ZGUtODEwNi1jMThlODA5YmNlZWI%3D
=> Tighten spacing on content single

packages/web-shared/components/FeatureFeed/Features/ActionBarFeature.js, packages/web-shared/components/FeatureFeed/Features/ChipListFeature.js, packages/web-shared/components/FeatureFeed/Features/ChipListFeature.styles.js, packages/web-shared/components/Searchbar/Search.styles.js, packages/web-shared/ui-kit/ContentCard/ContentCard.js
The ChipListFeature currently doesn't render well on content items (or non search feeds)
Style the chip list correctly
- Style like a chip, remove the "linky" bits.
- Remove the margin when rendering on a feed
- But add that margin back in when inside a searchbar. tricky! 
1. Inspect the chip list on the web embeds index, by clicking search and scrolling down.
3. Insect the chip list [on a content item](http://localhost:3000/?id=in-training-for-reigning-TWVkaWFDb250ZW50SXRlbS1kODI0Yjg0ZS00MDFkLTQ0NzAtOGFlNi1mYjU3Y2U4NWUwMmI%3D)
=> feat: Clean Up Chip List Feature

packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js, packages/web-shared/components/FeatureFeed/Features/HeroListFeature.styles.js, packages/web-shared/components/FeatureFeedList/FeatureFeedListGrid.js, packages/web-shared/hooks/useFeatureFeed.js, web-embeds/public/index.html
https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/7067994581
https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/7068020702
- Add the "series" tag to additional feature feed rendering paths
-  Add the series tag to HeroListFeatures
All in `web-embeds`
**[Visit Here](http://localhost:3000/watch?id=FeatureFeed-69cc8825bbc7612068c77496e3e2d9f48ad2b8906c455d95fdbba65e3b0fe30043d83c63592e2b9827777c0c311f2481db9397d1ae6fb376c2f14202e6d92b638ab01922febbefc30dc174b57b7ca74dc59cdae23fa90aaf5019a2bc059a7667b582f8523748bf7b65a7dd734facef30cdbcaedd05125ad417f2761552b1bec7bf3eb5b504800049c042fbed2b486e67bf20c6dba3150919951ed22a7f3407d54e398075fafc15017d209a78613921f14e985656cf4e2c6c6a42dcedadfd2085a49445dabd0ab1d8771668bb9029d81a7c800b70313977db52c878e89431bc212185c36fea12 …
=> Added series styling to more parts of the app

micro-service/README.md, packages/web-shared/client/apollosApiLink.js, web-embeds/README.md
Sometimes you are making changes in Admin and need to see in Web Embeds
Add documentation for how to disable caching
1. Start Admin and Web Embeds
2. Uncomment the `x-cache-me-not` header
3. Change a content item on Apollos Demo (on Admin) and nav to that same item in web embeds (or micro-service)
4. See the change come through immediately
https://github.com/ApollosProject/apollos-embeds/assets/72768221/0d41f7e2-af35-42d4-8f1d-b04e29ee06ec
=> chore: Bypass caching across all environments

packages/web-shared/embeds/FeatureFeed.js, packages/web-shared/utils/getContentFromURL.js
Links to events were broken
- Fix the component selection logic so it includes`events`
- Went a step further and consolidated the route -> component selection logic; it now only has a single path (previously there were two almost identical case statements, and an event fix had only been applied to one of them) 
on `web-embeds`...
1. http://localhost:3000/?id=Event-9d6c2738-5172-4e3f-b002-41a7c6d5038e
2. Also click around a bit and make sure navigation continues to work as expected :D
=> chore: Fix events via url

packages/web-shared/components/ContentChannel.js, packages/web-shared/components/FeatureFeed/Features/VerticalCardListFeature.js, packages/web-shared/components/FeatureFeedList/FeatureFeedListGrid.js
Clicking "view app" on an events feed would crash the modal.
Properly safely check for a `[0]`th video
In web embeds.
[This link should open](http://localhost:3000/?id=FeatureFeed-69cc8825bbc7612068c77496e3e2d9f48ad2b8906c455d95fdbba65e3b0fe30043d83c63592e2b9827777c0c311f2481db9397d1ae6fb376c2f14202e6d92b630b1aefda88740028cfaf9718c06bd477b2bf6e57d416060a3306d3148fd68544221ea9be28470896a68480bac5ef6a8662258bb83c903a024e75b6c250406df5cbf6d4a6b6744c3d05a2871bfbb59d326f7370d5ead1f716a378ab6e42fbec19e49af41f083726caa621ae4f9c5bc727e06b94904750a543b024d05e0dd8ab251c6168f7add50d215a37d8dd3d470680457999b80308ba7888b017f4715fc891f4eb6b420a6ff03a5fb8a0c32bb6c24c&action=viewall), and not display an error screen.
https://github.com/ApollosProject/apollos-embeds/assets/1637694/34ada1fe-a36c-4e8e-8e0b-7 …
=> Fix crash when opening / closing event feeds

packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js, packages/web-shared/components/FeatureFeed/Features/HorizontalMediaListFeature.js, packages/web-shared/components/FeatureFeed/Features/VerticalCardListFeature.js
Liquid needs some additional targeting options to safely target "View all" links and the associated icons. 
Added classNames to the "View All" links
n/a
n/a
=> Add classnames for View All buttons

packages/web-shared/components/FeatureFeedList/FeatureFeedListGrid.js, packages/web-shared/components/Searchbar/SearchResults.js
Two issues 
- Event items don't generate breadcrumbs
- Open an item from search adds to the breadcrumbs into infinity ♾️ 
- Don't dig into the `relatedNode` to use a title, the passed `title` is good enough #49 
- Reset the breadcrumbs when opening a item from search
From `web-embeds`
1. Tap around in search
- make sure the breadcrumbs are clearing when searching
- make sure tapping series children adds to the breadcrumbs as expected
2.Tap around on [this event feed](http://localhost:3000/?id=FeatureFeed-69cc8825bbc7612068c77496e3e2d9f48ad2b8906c455d95fdbba65e3b0fe30043d83c63592e2b9827777c0c311f2481db9397d1ae6fb376c2f14202e6d92b630b1aefda88740028cfaf9718c06bd477b2bf6e57d416060a3306d3148fd68544221ea9be28470896a68480bac5ef6a8662258bb83c903a024e75b6c250406df5cbf6d4a6b6744c3d05a2871bfbb59d326f …
=> Improve breadcrumbs

packages/web-shared/components/FeatureFeed/Features/ChipListFeature.js
[Chips to external links should open in a new tab](https://3.basecamp.com/3926363/buckets/32694519/card_tables/cards/7118163262)
If a link is pointed at a different origin, open it in a new tab. 
1. [Visit this item](https://apollos-web-embeds-git-chips-external-apollos-embeds.vercel.app/?id=the-way-of-worship-TWVkaWFDb250ZW50SXRlbS04OGMyNzkwMC03YWNkLTQ2MmEtYTc0Yi0zNTI1OGJhYTA4NWI%3D)
2. Tapping one of the chips should open a new tab. 
https://github.com/ApollosProject/apollos-embeds/assets/1637694/85a86f27-4d58-4fb9-966f-730f9ab9444f
=> feat: Chips should open in a new tab

packages/web-shared/components/Searchbar/Autocomplete.js
Liquid wants to show 8 items in search
Closes #
Show eight search results
1. [Visit the web embed](https://apollos-web-embeds-git-default-search-lim-164478-apollos-embeds.vercel.app/)
2. Search a term (like marriage)
=> tweak: Change default search limit to 8

packages/web-shared/components/AddToCalendar/AddToCalendar.js, packages/web-shared/components/AddToCalendar/AddToCalendar.styles.js, packages/web-shared/components/AddToCalendar/index.js, packages/web-shared/components/FeatureFeed/FeatureFeedComponentMap.js, packages/web-shared/components/FeatureFeed/Features/EventBlockFeature.js, packages/web-shared/components/FeatureFeed/Features/EventBlockFeature.styles.js, packages/web-shared/components/FeatureFeed/Features/index.js, packages/web-shared/hooks/useFeatureFeed.js
No event block in web, part of cycle goals
Add event block
https://github.com/ApollosProject/apollos-embeds/assets/103927/151dc085-931d-40ab-81bf-fe7bab49768e
1. On staging admin create a content item with an event block
2. While pointed at staging, open that content item in the web service
=> Add Event Block

packages/web-shared/components/ContentSeriesSingle.js
too much space between child vertical cards https://github.com/ApollosProject/apollos-embeds/issues/179
fix gap in child series
1. go to link -> http://localhost:3000/watch?id=the-way-Q29udGVudFNlcmllc0NvbnRlbnRJdGVtLTdmMGMzOTA0LTc1MDQtNGUwYi05MzFhLWFjNTliNDA3NDRhYQ%3D%3D
2. Check gap between child items in series
=> fix: too much space between child vertical cards

packages/web-shared/components/ContentSingle.js, packages/web-shared/components/FeatureFeed/Features/HorizontalCardListFeature.js
When clicking events from a link the breadcrumbs are broken https://github.com/ApollosProject/apollos-embeds/issues/181
breadcrumb issues - remove last item from  breadcrumb on ContentSingle
title issue - add missing title param
1. Navigate to series item 
2. Keep selecting single content items of that series
https://github.com/ApollosProject/apollos-embeds/assets/28708210/b9dca95c-6421-47b7-80fc-86b2f20f9cc3
=> fix: when clicking events from a link the breadcrumbs are broken

packages/web-shared/components/ContentSingle.js
Spacing under event title https://github.com/ApollosProject/apollos-embeds/issues/180
fix title spacing
1. Navigate to event content
2. Check spacing between title and event data
3. Sample event data
`<div
data-type="FeatureFeed"
data-church="liquid_church"
data-feature-feed="FeatureFeed:e5d913ee-0f28-45a3-8f71-f5ce2ae6cb3b"
data-placeholder="What are you looking for?"
data-modal="true"
class="apollos-widget"
></div>`
=> fix: spacing under event title

packages/web-shared/components/ContentSingle.js
We're making LOTS of invalid requests to the server. This is causing a lot of unnecessary load on the server.
Skip making requests to the server if there's no feed ID
Not really sure...
=> skips feature feed query if no ID

packages/web-shared/components/ContentSingle.js
I believe Google is flagging many liquid pages as duplicates
Use the canonical URL prop to convince google that certain pages are the same. 
1. Start the web embeds test server
2. Visit a content item
3. Look for the canonical link tag,.
=> feat: Add canonical url

micro-service/src/App.js, packages/web-shared/components/AppHeader/AppHeader.js, packages/web-shared/components/AppHeader/index.js, packages/web-shared/components/Profile/Profile.js, packages/web-shared/components/Profile/Profile.styles.js, packages/web-shared/components/Profile/ProfileButton.js, packages/web-shared/components/Searchbar/Searchbar.js
You can't login on micro service. We will need login for user commenting.
Add an AppHeader and Profile button.
1. `cd micro-service && yarn dev`
2. navigate to a content item (or don't - this shows on the error home page)
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/Iqv8SYVwCDX0dUbjBiDz/1cccf6b1-d5b4-4465-aafe-9a46bf185006.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Iqv8SYVwCDX0dUbjBiDz/1cccf6b1-d5b4-4465-aafe-9a46bf185006.mp4">login.mp4</video>
=> Add AppHeader and Login to MicroService

micro-service/src/index.css, packages/web-shared/components/Comments/AddComment.js, packages/web-shared/components/Comments/Comment.js, packages/web-shared/components/Comments/Comments.js, packages/web-shared/components/Comments/index.js, packages/web-shared/components/ContentSingle.js, packages/web-shared/fragments/fragments.js, packages/web-shared/providers/AuthProvider.js, packages/web-shared/ui-kit/Avatar/Avatar.js, packages/web-shared/ui-kit/Button/Button.js, packages/web-shared/ui-kit/Button/Button.styles.js, web-embeds/public/index.html, web-embeds/src/index.css
There's no commenting on web
Add commenting on web! Built with quick and easy components, tried to handle most states/things but within constraints of current code standards.
1. Open a content item with discussions
2. Tap new discussion button
3. Add comments
4. Do the same on a content item w/o discussions
💸
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/Iqv8SYVwCDX0dUbjBiDz/8d4c27ed-22ac-4780-bbf5-78537882b0df.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Iqv8SYVwCDX0dUbjBiDz/8d4c27ed-22ac-4780-bbf5-78537882b0df.mp4">demo comments.mp4</video>
=> Add commenting to web

package.json, packages/web-shared/components/Comments/AddComment.js, packages/web-shared/components/Comments/Comment.js, packages/web-shared/components/Comments/Comments.js, packages/web-shared/components/ContentSingle.js, packages/web-shared/components/Profile/ImageUploader.js, packages/web-shared/components/Profile/ProfileButton.js, packages/web-shared/components/Searchbar/Searchbar.js, packages/web-shared/package.json, yarn.lock
Web embeds broke
- Adjust yarn workspace settings to treat microservice and webembeds as packages: this should resolve dep issues better
- import React everywhere I didn't: I guess you still have to import React on web-embeds (but you don't on micro-service)
- Fix Comments layout/styles to work on web embeds properly
1. cd `web-embeds`, `yarn dev`. 
2. cd `micro-service`, `yarn dev`.
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/Iqv8SYVwCDX0dUbjBiDz/86cf4b9e-139d-4797-9e36-cb578ec3561a.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/Iqv8SYVwCDX0dUbjBiDz/86cf4b9e-139d-4797-9e36-cb578ec3561a.mp4">web embed commenting fix.mp4</video>
=> Fix Web Embeds

packages/web-shared/components/Searchbar/Autocomplete.js, packages/web-shared/components/Searchbar/SearchResults.js
Since we have two indices, search results always return with web page results first, and content item results second.
This makes it hard to the user to understand which results to look at, and without any other result context (like summaries) the quality of the search results feel very poor.
1. Combine multi-index results into a single array. This is hacky, and isn't a permanent solution. Best case - the results end up in a much better order. Worse case - they end up in a similar order to they are already. 
2. Add summary/subtitles to results
3. Remove "Search history" section if you have search results
As a follow up, @vinnyjth is going to document work to be done on the shovel to create a new, combined index that we can start tweaking to more dramatically improve search results.
Also, …
=> Improve search result sorting and add subtitles to results

packages/web-shared/components/Searchbar/Autocomplete.js, packages/web-shared/components/Searchbar/SearchResults.js
On production if you click on a web page search result nothing happens.
Also, clicking on "recent searches" does nothing.
Fix web link clicks
Kill recent searches - too many complaints about it
1.
2.
=> Fix linking

packages/web-shared/ui-kit/Longform/Longform.styles.js
#216 
Fixed Line Height
1. Add a HTML content page with Long text H1 tags. with the auto wrap line height should be fine.
2.
=> Fixed sharing content changes the formatting #216

packages/web-shared/components/Searchbar/Searchbar.js
Background page scroll under search result
Closes https://github.com/ApollosProject/apollos-embeds/issues/219
fix scroll issue in mobile search
1. Open web embeds search in mobile browser
2. Check background page scroll under search result
https://github.com/ApollosProject/apollos-embeds/assets/28708210/c45bc555-a784-4f78-9713-474f03b30995
=> fix: search is busted

packages/web-shared/components/Searchbar/Search.styles.js
Search is busted
Closes https://github.com/ApollosProject/apollos-embeds/issues/219
set panel height 80% from vh to make scrollable 
1. Open web embeds search in mobile browser
https://github.com/ApollosProject/apollos-embeds/assets/28708210/cb62172f-7e2e-43a3-a4ef-c1066875bfe2
=> fix: search is busted reopen

packages/web-shared/components/ContentSingle.js, packages/web-shared/components/FeatureFeed/Features/HeroListFeature.js, packages/web-shared/components/Modal/Modal.js, packages/web-shared/components/Wordmark/Wordmark.js, packages/web-shared/ui-kit/ContentCard/ContentCard.js
It's currently very difficult to get "into" the modal context when browsing web embeds. Also, none of our cards are selectable b/c they use divs. 
Refactoring to use `<a`s looked like an uphill slog with potentially backwards incompatible changes, so I opted to add the correct aria roles to our a/divs.  Let's not make this mistake on new-web 😅 
1.Open our web embeds tester
2. Poke around with voiceover on. 
1.
2.
https://github.com/user-attachments/assets/2f972dad-b4fe-41c3-b2f1-7425835af237
<!--
=> Fix basic aria states

packages/web-shared/providers/ModalProvider.js
Closes #235 
Clear the modal's content when closing the modal to remove the video from the page and thus stop it playing.
1. Run Admin, Cluster, micro-service, and web-embeds locally
2. In Admin, create or find a Feed with videos
3. Click the "Share" button and copy the embed
4. Embed the code somewhere (`web-embeds/public/index.html` is a good place)
5. Check out the embed in your browser, open a video, start the video, and then close the modal while the video is playing
The video and audio should stop playing.
https://github.com/user-attachments/assets/9eab6a6a-8814-4daf-a8a0-14ceddb8d4c6
=> fix: clear modal content when closing to stop videos playing

packages/web-shared/components/Profile/Profile.js
Closes #234 
Use church's configured icon background color
1. Open an embed and check the icon color
2. Open Admin, click the user icon in the bottom left, then click Organization Profile
3. Change the Brand Icon Background Color to something different than any of the existing colors
4. Refresh the embed, note the change in icon color
=> Apo 1016 seacoast web icon background in search

packages/web-shared/components/Searchbar/Searchbar.js
Closes #232 
The "Hey!" part of the prompt was being spaced out excessively by the `&nbsp;` for reasons I shall allow to remain unknown. Additionally, the width of the placeholder was not being calculated properly, resulting in a `width` value of `[object Object]`.
Instead of spacing the prompts with a `&nbsp;`, use CSS to give it a right margin. Also calculate the placeholder width properly and set it via CSS.
I haven't been able to reproduce this locally, only was able to test by directly editing the source in the browser to remove the `&nbsp;` and use `margin-right: 0.35ch` instead.
| --- | --- |
| <img width="398" alt="Screenshot 2024-11-22 at 10 17 41 AM" src="https://github.com/user-attachments/assets/0842ec8c-fbd4-43a1-ac9d-818c6cc458ef"> | <img width="407" …
=> Apo 1022 seacoast search bar alignment

packages/web-shared/components/Profile/Profile.js, packages/web-shared/components/Profile/Profile.styles.js, packages/web-shared/components/Profile/ProfileButton.js, packages/web-shared/components/Searchbar/Searchbar.js, packages/web-shared/embeds/Main.js, packages/web-shared/providers/AppProvider.js, packages/web-shared/providers/SearchProvider.js, web-embeds/README.md, web-embeds/src/App.js
Closes #233 
The profile popup width is based on the viewport width by default, and is absolutely positioned so its width isn't controlled by its container.
Implement a new data prop `data-search-profile-size` which takes a CSS width string, allowing the consumer to specify whatever width they need.
Also nudge the popup to the right 15px to align it with the search bar.
I haven't been able to reproduce this locally, only was able to test by directly editing the source in the browser to apply the styling changes. 
With `data-search-profile-size` set to `365px`:
=> feat: allow for specifying a custom width for the profile popup

packages/web-shared/components/Modal/Modal.js, web-embeds/public/index.html
Fix APO-1089
Added a class name to the Modal component for better CSS targeting
1. Open the web-embeds demo page
2. Verify the modal has the class name "apollos-modal"
=> feat: add a classname for apollos-modal

packages/web-shared/components/Modal/Modal.js, packages/web-shared/providers/AppProvider.js, packages/web-shared/providers/NavigationProvider.js, web-embeds/public/index.html, web-embeds/src/App.js
=> fix: feature flag apollosId search param behind a new data tag

packages/web-shared/components/Searchbar/SearchResults.js, web-embeds/public/index.html
Search Feed needs margin
Add margin to Search Feed
1. `cd web-embds`
2. `yarn dev`
1. Have Cluster running locally
1. Open the Search Embed
1. See margin around the feed
Before | After
---|---
=> feat: add base margin to search feed

packages/web-shared/components/Searchbar/Searchbar.js
Closes APO-1159
Closes #247 
Closes #248 
Removed unnecessary scroll position restoration in the Searchbar component when closing the search overlay. This prevents unwanted scrolling behavior when the search interface is interacted with.
1. Click on a Search Embed
1. Type in the Search Embed
1. Verify that the page maintains its current scroll position without jumping
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a href="https://app.graphite.dev/media/video/cC1wbzju6tRNdXbxLHUd/ff53aa53-4616-4017-8bad-c7250a33dc14.mp4">
</a>
</div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/cC1wbzju6tRNdXbxLHUd/ff53aa53-4616-4017-8bad-c7250a33dc14.mp4">before.mp4</video>
<div class='graphite__hidden'>
<div>🎥 Video uploaded on Graphite:</div>
<a …
=> fixed jump when clicking search

.github/workflows/deploy.yml, web-embeds/package.json, web-embeds/src/index.js
We need to know the embeds version a website is using for debug purposes
=> expose embeds version

packages/web-shared/analytics/amplitude.js, packages/web-shared/providers/AnalyticsProvider.js
This pull request includes several changes to improve the analytics tracking and querying functionality in the `packages/web-shared` module. The most important changes include updating the initialization of analytics, adding new GraphQL queries, and modifying the `AnalyticsProvider` component to better handle authentication and environment checks.
* [`packages/web-shared/analytics/amplitude.js`](diffhunk://#diff-82b1998460a9d1fb52e9f9a68da1511626b7e9e76186aa461e65197d126739b9L7-R7): Changed the `init` function to accept `currentUser` as `null` instead of `false` for better consistency.
* [`packages/web-shared/providers/AnalyticsProvider.js`](diffhunk://#diff-6d497aa7d5306b74a0d62e5c725a70527ae7625ccf180190abd216af9ca83bdeR6-R14): Renamed the `GET_ANALYTICS_USER` query to …
=> stop making currentuser requests not logged in

packages/web-shared/components/VideoPlayer/VideoPlayer.js
This pull request includes a small change to the `VideoPlayer` component in the `packages/web-shared` directory. The change modifies the condition for identifying YouTube videos by checking for a broader match in the URI.
* [`packages/web-shared/components/VideoPlayer/VideoPlayer.js`](diffhunk://#diff-d7412c3d7876a3cea451786f746381e19896808e8cc5345893602b6dab8928a0L42-R42): Updated the condition to identify YouTube videos by checking if the URI includes 'youtu' instead of 'youtube.com'.
=> fix youtube links
